name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -  name: Set up Git Repository
       uses: actions/checkout@v2
     
    - name: Set up Enviroment
      run: sudo apt install texlive-full

    - name: Run a pdfLatex build
      run: pdflatex DP_Matějka_Jan_2020
      
    - name: Upload Data as Artifact
      uses: actions/upload-artifact@master
      with:
        name: PDF Output
        path: DP_Matějka_Jan_2020.pdf

    - name: Cat Log
      if: failure()
      run: |
        cat DP_Matějka_Jan_2020.log
        ls -la
