name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: LaTex image
    runs-on: ubuntu-latest

    steps:
    -  name: Set up Git Repository
       uses: actions/checkout@v2

    - name: Set up Enviroment
      run: sudo apt install texlive texlive-latex-base texlive-latex-extra texlive-extra-utils texlive-lang-czechslovak texlive-bibtex-extra

    - name: Run pdflatex - prerender .aux file
      run: pdflatex main

    - name: Run bibtex - rendering bibliography file
      run: bibtex main.aux

    - name: Run pdflatex - rendering for sure
      run: pdflatex main

    - name: Run pdflatex - final rendering
      run: pdflatex main

    - name: Rename output PDF file
      run: mv main.pdf DP_Matějka_Jan_2020.pdf

    - name: Upload Data as Artifact
      uses: actions/upload-artifact@master
      with:
        name: DP_Matějka_Jan_2020
        path: DP_Matějka_Jan_2020.pdf

    - name: Cat Log
      if: failure()
      run: |
        cat DP_Matějka_Jan_2020.log
        ls -la
