name: Build_and_Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: LaTex image
    runs-on: ubuntu-latest

    steps:
    -  name: Set up Git Repository
       uses: actions/checkout@v2

    - name: Set up Enviroment
      run: sudo apt install texlive texlive-latex-base texlive-latex-extra texlive-extra-utils texlive-lang-czechslovak texlive-bibtex-extra

    - name: Run pdflatex - prerender .aux file
      run: pdflatex main

    - name: Run bibtex - rendering bibliography file
      run: bibtex main.aux

    - name: Run pdflatex - rendering for sure
      run: pdflatex main

    - name: Run pdflatex - final rendering
      run: pdflatex main

    - name: Rename output PDF file
      run: mv main.pdf DP_Matějka_Jan_2020.pdf

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@master
      with:
        name: DP_Matejka_Jan_2020.zip
        path: DP_Matějka_Jan_2020.pdf

    - name: Semver Release
      uses: K-Phoen/semver-release-action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_branch: master

    - name: Upload PDF to release assets
      uses: softprops/action-gh-release@v1
      with:
        files: DP_Matějka_Jan_2020.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cat Log
      if: failure()
      run: |
        cat main.log
        ls -la
