name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: LaTex image
    runs-on: ubuntu-latest

    steps:
    -  name: Set up Git Repository
       uses: actions/checkout@v2

    - name: Set up Enviroment
      run: |
        sudo apt install texlive texlive-latex-base texlive-extra-utils texlive-lang-czechslovak texlive-bibtex-extra
        sudo apt install python-pygments

    - name: Run Arara
      run: arara DP_Matějka_Jan_2020

    - name: Upload Data as Artifact
      uses: actions/upload-artifact@master
      with:
        name: PDF Output
        path: DP_Matějka_Jan_2020.pdf

    - name: Cat Log
      if: failure()
      run: |
        cat DP_Matějka_Jan_2020.log
        ls -la
