name: Build_and_Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on LaTex image and Release
    runs-on: ubuntu-latest

    steps:
    -  name: Set up Git Repository
       uses: actions/checkout@v2

    - name: Set up Enviroment
      run: sudo apt install texlive texlive-latex-base texlive-latex-extra texlive-extra-utils texlive-lang-czechslovak texlive-bibtex-extra

    - name: Run pdflatex - prerender .aux file
      run: pdflatex main

    - name: Run bibtex - rendering bibliography file
      run: bibtex main.aux

    - name: Run pdflatex - rendering for sure
      run: pdflatex main

    - name: Run pdflatex - final rendering
      run: pdflatex main

    - name: Rename output PDF file
      run: mv main.pdf DP_Matějka_Jan_2020.pdf

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@master
      with:
        name: DP_Matejka_Jan_2020.zip
        path: DP_Matějka_Jan_2020.pdf

    - name: Release from Artifacts to Releases
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: ./
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cat Log
      if: failure()
      run: |
        cat main.log
        ls -la
